### ISSUE TITLE
NullPointerException on IdentifiableCookie.hashCode

### ISSUE THREAD

**Issue by j05u3** [franmontiel/PersistentCookieJar#35]
I received this stack trace from a user:
```Caused by java.lang.NullPointerException:
com.franmontiel.persistentcookiejar.cache.IdentifiableCookie.hashCode (IdentifiableCookie.java:65)
java.util.HashMap.remove (HashMap.java:624)
java.util.HashSet.remove (HashSet.java:173)
com.franmontiel.persistentcookiejar.cache.SetCookieCache.addAll (SetCookieCache.java:37)
com.franmontiel.persistentcookiejar.PersistentCookieJar.<init> (PersistentCookieJar.java:38)```

**Comment by j05u3** [comment]
It may be related to #4 ?

**Comment by franmontiel** [comment]
I don't think it is related to #4 because on version 1.0.1 there is a null check when decoding cookies from persistence. Are you using the latest version?

**Comment by j05u3** [comment]
I was using 1.0.0 at the moment of receiving that stack trace. It must be that then, thank you.

**Comment by thelittlefireman** [comment]
Hi,
i juste received the same error on version 1.0.1 : 
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
       at com.franmontiel.persistentcookiejar.cache.IdentifiableCookie.hashCode(SourceFile:65)
       at java.util.Collections.secondaryHash(Collections.java:3427)
       at java.util.HashMap.remove(HashMap.java:616)
       at java.util.HashSet.remove(HashSet.java:173)
       at com.franmontiel.persistentcookiejar.cache.SetCookieCache.a(SourceFile:37)
       at com.franmontiel.persistentcookiejar.PersistentCookieJar.<init>(SourceFile:38)`
