### ISSUE TITLE
SharedPrefsCookiePersistor.loadAll() - SerializableCookie InvalidClassException

### ISSUE THREAD

**Issue by curlyfrie** [franmontiel/PersistentCookieJar#4]
Hi,

thx for providing this cookie jar :)

i had some troubles with the SerializableCookie, because it has no serialVersionUID definied.
Therefore, if something in the class is changed (or in my case i updated gradle) the uid changed and the cookies cannot be deserialized.

Furthermore, in SharedPrefsCookiePersistor.loadAll a 'null' cookie is added to the list which causes a NullPointerException later on:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.Cookie.name()' on a null object reference
	   at com.franmontiel.persistentcookiejar.cache.IdentifiableCookie.hashCode(IdentifiableCookie.java:65)
	   at java.util.Collections.secondaryHash(Collections.java:3427)
	   at java.util.HashMap.put(HashMap.java:385)
	   at java.util.HashSet.add(HashSet.java:95)
	   at java.util.AbstractCollection.addAll(AbstractCollection.java:76)
	   at com.franmontiel.persistentcookiejar.cache.SetCookieCache.updateCookies(SetCookieCache.java:46)
	   at com.franmontiel.persistentcookiejar.cache.SetCookieCache.addAll(SetCookieCache.java:36)
	   at com.franmontiel.persistentcookiejar.PersistentCookieJar.<init>(PersistentCookieJar.java:38)`

So i suggest to maybe add `private static final long serialVersionUID = 1L;` to SerializableCookie
and maybe something like this in SharedPrefsCookiePersistor.loadAll():

```
if (cookie != null) {
	cookies.add(cookie);
} else {
	//cannot decode cookies from sharedPrefs (serialize id changed e.g.); clear all
	clear();
	break;
}
```
Looking forward to hear your thoughts on this issue.

**Comment by franmontiel** [comment]
Yes, you're right, but the change in the generated serialVersionUID seems to be related with the activation/deactivation of instant run, so it should not affect to any release build.

I'm going to make an update forcing the class to use the serialVersionUID = -8594045714036645534L (it is the generated one when not using instant run). I think that this should solve the problem.

**Comment by curlyfrie** [comment]
Ok thx.
Although I would also suggest to make sure no 'null' cookie is added in loadAll..
