### ISSUE TITLE
Invalid Cast

### ISSUE THREAD

**Issue by Varun-Sethu** [franmontiel/PersistentCookieJar#51]
Hi! Whenever I try and use your library i always get the following issue
```java
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
at com.franmontiel.persistentcookiejar.persistence.SharedPrefsCookiePersistor.loadAll(SharedPrefsCookiePersistor.java:48)
at com.franmontiel.persistentcookiejar.PersistentCookieJar.<init>(PersistentCookieJar.java:38)
```

I have no idea what is going on and I was wondering if anyone could help me out.
To provide some context the following is the HTTP class I use to preform requests...
```java
public class HTTP {

    // Cookie manager
    OkHttpClient client;
    ClearableCookieJar cookieJar;

    public HTTP(SharedPreferences preferences) {
        this.cookieJar =
                new PersistentCookieJar(new SetCookieCache(), new SharedPrefsCookiePersistor(preferences));

        // Set up the okhttp client
        this.client = new OkHttpClient.Builder()
                .cookieJar(cookieJar)
                .build();
    }

    public Response performRequest(Request request) throws Exception {
        // Perform the request
        Response response = client.newCall(request).execute();
        // Save the cookies
        return response;
    }
}
```

**Comment by franmontiel** [comment]
Are you using a sharedPreferences already containing other values? If it is the case that's your problem. 
I will update the documentation accordingly once I have some spare time.

**Comment by Varun-Sethu** [comment]
Yes I am... Thank you so much, I will test it now.

**Comment by Varun-Sethu** [comment]
Yep it works perfectly! Thanks for the help!
